### ISSUE TITLE
Mod not working with need for speed (steam) ERROR can't create already existing file

### ISSUE THREAD

**Issue by Cimmerian-Iter** [Dyvinia/DatapathFixPlugin#11]
Hey, I have used this plugin and it works for need for speed heat, mods are loaded, but when I try to load mod with need for speed, it doesn't work. And when I check logs it says that datapathfix couldn't create a file that was already existing.

Any solutions? Thanks

**Comment by Dyvinia** [comment]
send a screenshot

**Comment by slowthgt** [comment]
Not the same game, (mine is on Mirror's Edge: Catalyst), but I did get the same error, with the game not loading mods.
![raw](https://user-images.githubusercontent.com/8595871/223779082-3f04cc85-bf0d-4107-90e5-db695ff1eddc.png)
(Portuguese for "Error: Cant create already existing file.")

**Comment by slowthgt** [comment]
Found the issue, seems to stem from doing a file integrity check, interfering with the .orig.exe copy. Deleting the .orig.exe seems to have done the trick.

**Comment by chromKa** [comment]
Me too.
Delete .orig file in game - fix this problem.
Need fix plugin.

**Comment by Dyvinia** [comment]
if it can't delete .orig, then it does not have the proper permissions to do so

**Comment by Alfa141** [comment]
Guys, I have this problem when I click in Launch in Need For Speed Unbound, when I start without Data Path, launches Ok
![image](https://github.com/Dyvinia/DatapathFixPlugin/assets/127799826/5c9e455e-89a0-4573-9301-19814d0c0b82)
