### ISSUE TITLE
Frosty Mod Manager 1.0.6.2 Alpha "Cannot find Datapathfix.exe"

### ISSUE THREAD

**Issue by AfteglowFlux** [Dyvinia/DatapathFixPlugin#12]
This is all related to NFS Heat Mods

When I try this data fix it used to work on 1.2.0.0 Datapathfix.dll and 1.0.0.0 Datapathfix.exe until EA Launcher forced me to do the latest update yesterday. I am not the only one with this issue, I was running Frosty Mod Manager 1.0.6.1 full release before with this version of Datapathfix.

I updated to your version of Datapathfix 1.5.1. While the task goes through on 1.0.6.1 Frosty Mod Manager with no error, no mods load to the game, not even once.

It says "Cannot find Datapathfix.exe" (pic 1) on 1.0.6.2 Alpha. I have put the Datapathfix.exe and Datapathfix.dll in the Plugins folder for Frosty Mod Manager but does not detect it at all when launching NFS Heat. 1.0.6.2 Alpha attempts to load the mods on each launch but the Datapathfix is not functioning to finish the file movement. It does detect the Datapathfix plugin in Tools for this version of Frost Mod Manager as well (pic 2). It's really bizarre and needs to be looked into. Thanks.

If you have a solution would be greatly appreciated.
![Datapathfix Error 1 0 6 2 ALPHA](https://user-images.githubusercontent.com/128315023/226195374-27164b7c-9c54-43cb-95a9-cb9134529f3f.png)
![Datapathfix in Tools 1 0 6 2 ALPHA](https://user-images.githubusercontent.com/128315023/226195376-48f3380c-d785-42de-baf2-69b0651593fb.png)

**Comment by Dyvinia** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13797470/217099203-aef1e38e-c61e-4094-8fe2-d9523ff43061.gif)

**Comment by AfteglowFlux** [comment]
I already stated I put them in the folder. Anyways. It was not the issue. Nothing solved it on Alpha 1.0.6.2. It just does not work. I did however get 1.0.6.1 full release to work with Datapathfix 1.5.1 by deleting the NeedForSpeedHeat.orig or NeedForSpeedHeat.old (depending on what shows up) and set the main NeedForSpeedHeat.exe (main .exe) to run as admin. I have loaded the game 7 times in a row now, with mods. To streamline the process and get a lot less Admin prompts I turned them off in Windows settings. You will however still get an EA Launcher Admin approval to accept before game launch. I did not have to do this on version 1.2.0.0/1.0.0.0. let alone run the NeedForSpeedHeat.exe as admin.

Next time attempt to solve the issue not just share a gif that I already know how to do & insult my intelligence. You are welcome btw. Thanks for absolutely nothing.

Files mentioned below. If .old is not present .orig will be in the same spot. You'll need to delete that file so it can reset the data path sequence. This worked on 1.0.6.1 full release not 1.0.6.2 Alpha for Frost Mod Manager.
![File Path -  old Example](https://user-images.githubusercontent.com/128315023/226198184-2677b0f5-eeb5-43de-b6e8-0fb775e279da.png)

**Comment by Dyvinia** [comment]
`Cannot find Datapathfix.exe` is 100% the user installing the files wrong, feel free to check the code to see when that error would pop up if you do not believe me.

**Comment by AfteglowFlux** [comment]
I delt with troubleshooting for several hours and had the files in the right place. Frosty Mod Manager > Plugins. exactly as your useless response stated. I did not ask for how to put it in the folder. I asked for help on why it wasnt loading mods on 1.0.6.1 and why the error occurred on 1.0.6.2 Alpha. Go download 1.0.6.2 Alpha and try it yourself! It didnt work on 2 different PC's on 1.0.6.2.....
