### ISSUE TITLE
Not launching with steam

### ISSUE THREAD

**Issue by cpuccino** [Dyvinia/DatapathFixPlugin#13]
I'm using Frosty 1.0.6.2 (admin) w/DatapathFix v1.5.1 - ME: Andromeda on steam. EA desktop launches then restarts then nothing happens.

edit: deleting the moddata seems to have fixed it. Maybe it's a good idea to add this to the troubleshooting section?

**Comment by Doobies-lab** [comment]
where is moddata? I cant find it and the same problem is happening

**Comment by Doobies-lab** [comment]
wait i realized this isnt for mirrors edge catalyst

**Comment by Dyvinia** [comment]
Deleting ModData is relevant to Frosty itself, not to this plugin
