### ISSUE TITLE
Issue with EA - STEAM - FROSTY interconnectivity

### ISSUE THREAD

**Issue by cristian1991** [Dyvinia/DatapathFixPlugin#15]
I'm playing Unbound on EA App via the Steam client to be able to use ps5 controller. 

If i set the nfsunbound.exe to run as admin from file properties i can run the game with frosty and datapathfix but the ea desktop app relaunches, and steam doesn't get to load so no more controller. 

If i run without admin on file the mod doesn't load at all. 

Also, if mods do load, the game keeps accelerating and braking at the same time.

EDIT: I've figured it all out! Seems the whole issue was being caused by Steam. Setting the NFSUNBOUND.exe to run as admin from compatibility mode, running the EA app normally (nor from steam) and using DS4Windows (wired) for the controller emulation did the trick

**Comment by Dyvinia** [comment]
interesting, dpfix is really just a hack so any issues like this would probably just be due to how the hack is carried out
