### ISSUE TITLE
disfunctional

### ISSUE THREAD

**Issue by breakdowngamesYT** [Dyvinia/DatapathFixPlugin#2]
when i attempt to launch bf2 using frosty ea desktop or steam after having this installed it closes ea desktop and the game never launches

**Comment by AZeonZaku** [comment]
I've got tis as well, looked in task manager it seems the process is being suspended

**Comment by wannkunstbeikor** [comment]
u probably didnt do everything it says in read me

**Comment by Dyvinia** [comment]
?
