### ISSUE TITLE
Executable replacing and Running Games in Background 

### ISSUE THREAD

**Issue by kaosTwo** [Dyvinia/DatapathFixPlugin#4]
I am having a couple of issues with DatapathFix. One has already been logged, and that's the renaming and replacing of the DragonAgeInquisition.exe (DragonAgeInquisition.exe.old), and that this is causing the game to run in the background until I end the task according to Task Manager. I'm wondering if the two are related in some way, but I have zero brain for deeper level stuff.

**Comment by Dyvinia** [comment]
>  the renaming and replacing of the DragonAgeInquisition.exe (DragonAgeInquisition.exe.old)
that is intended, it does some shuffling of files to launch the game with mods

> and that this is causing the game to run in the background until I end the task according to Task Manager.
Can you download this version of the plugin and enable debug in the datapathfix settings within frosty mod manager options. 
There should be cmd windows appearing while launching, please tell me if there are any errors.
[DPFixTest.zip](https://github.com/Dyvinia/DatapathFixPlugin/files/10562891/DPFixTest.zip)

**Comment by Dyvinia** [comment]
Try 1,4,0 instead of the zip file above
