### ISSUE TITLE
Question regarding Newtonsoft.Json;

### ISSUE THREAD

**Issue by KittySkin** [Dyvinia/DatapathFixPlugin#5]
Which version of it are you using?
I downloaded the project and ended up updating usages of it with the latest version since the methods changed.
Mind to provide the exact version so I can just fork and contribute without the hassle of modifying the source before committing to comply with your version?

The exact function is FileSystem that has been replaced with FileSystemManager

**Comment by Dyvinia** [comment]
datapathfix is currently based off of frosty 1.0.6.2
