### ISSUE TITLE
Issue with DAI not launching on 1.4.1

### ISSUE THREAD

**Issue by Sleetzer** [Dyvinia/DatapathFixPlugin#6]
DAI won't launch on 1.4.1. I have to delete the moddata folder and close origins AND close frosty (I use steam btw) then reapply the mods to launch it.

**Comment by kerb9729** [comment]
My game (Dragon Age Inquisition, on PC/Win11 Steam, which in turn launches the EA app) launches on 1.4.1.   I do not see a terminal window popping up which I find strange.  But my mod appears to be working.

**Comment by gilangr05** [comment]
![update](https://user-images.githubusercontent.com/48384113/216628278-9770ec10-8a1a-45be-a52a-7788b63513d1.png)
well, thanks.
i can't play nfs heat anymore because this

**Comment by Dyvinia** [comment]
@kerb9729 
> I do not see a terminal window popping up which I find strange.
There is no reason why you would see one at all

**Comment by Dyvinia** [comment]
@Sleetzer 
Does it work with previous versions

**Comment by kerb9729** [comment]
@Dyvinia I am just used to seeing one.  On subsequent launch I do see it.  Probably just a fluke earlier.  So the plugin is working perfectly on my os/game/launcher combination. (Thank you for creating and sharing it!)

**Comment by redundantcee** [comment]
Not trying to hijack this thread or anything, but having the same issue with DAI not launching after updating to 1.41. I enabled debug but didn't get any errors, just a command prompt with some general information. I'm launching from Steam if it matters. When I do launch it Steam says it's running, and I can see DAI running but under Frosty Mod Manager in task manager, but it never seems to start.

Still able to get mods working with the old mod manager, so not a huge deal. And this plugin has been great for ME: Andromeda!

**Comment by Dyvinia** [comment]
@redundantcee 
Steam seems weird, some games seem to have EASteamProxy.exe being the parent to the process, which causes dpfix to get stuck. The internet seems to suggest that the proxy is used to inject the steam overlay, do you have steam overlay enabled by chance?

**Comment by redundantcee** [comment]
I do, but I don't think it ever gets to a point where it would load. I'll try disabling it though and see what happens.

Also noticed when I launch MEA I get two command prompts, the first with the general info, then another saying it's launching MEA with mods. I never get the second one for DAI though.

**Comment by redundantcee** [comment]
Same result with steam overlay disabled. I did notice that if I go into task manager and then into details the Dragonageinquisition.exe process status is 'suspended'.

![image](https://user-images.githubusercontent.com/124591929/217101914-2c1438cc-127e-4601-b1ac-34834476410c.png)

**Comment by andreimsuciu** [comment]
i have the exact same issue with DAI running through steam and EAPlay

**Comment by oliverpl** [comment]
Just wanted to mention that I downloaded and installed the plugin, then launched the game as normal through Frosty. All of my mods started working again, no issues for me. For additional context, I own Dragon Age Inquisition: Game of the Year edition and use the EA App.

**Comment by Dyvinia** [comment]
confirms that disabling in game ea desktop overlay fixes this issue
