### ISSUE TITLE
SW Battlefront 2 stuck on running

### ISSUE THREAD

**Issue by EdinelCandido** [Dyvinia/DatapathFixPlugin#7]
Hi,

I added the datapath plugin to frosty, which changed the game to be displayed as "datapath".
I did what was suggested (closed every instance of EA, frosty and steam - actually restarted the pc) and tried to run it normally (directly on steam), however it wont launch.

Any help would be appreciated :)

**Comment by Dyvinia** [comment]
4th bullet point in troubleshooting section
