### ISSUE TITLE
Doesn't work with frosty 1.0.7.0

### ISSUE THREAD

**Issue by bisquickpancakemix** [Dyvinia/DatapathFixPlugin#9]
This fix only works for version 1.6.1.0 of frosty mod manager or older, but I play need for speed unbound which is only compatible with 1.0.7.0 or newer, but when I try launching it says "unhandled exception occured" will there be a fix for the newer version of frosty ? Thanks

**Comment by Dyvinia** [comment]
ill do it whenever 1.0.7 has a public release
